feat: add function for billing per identifier instead of only source
esx-framework/esx_billing pull request #19
Opened 2024-06-19 20:17 UTC by Z3rio

2024-06-19 22:00 UTC, Gellipapa requested changes
Hi! Please do this little refactor but code cool thanks for improvment to esx_billing.

2024-06-19 22:00 UTC, Gellipapa commented on server/main.lua
> +					MySQL.insert('INSERT INTO billing (identifier, sender, target_type, target, label, amount) VALUES (?, ?, ?, ?, ?, ?)', {xTarget.identifier, senderIdentifier, 'society', sharedAccountName, label,
Here you should also use the logic I wrote in the comment below because the query is the same.

2024-06-19 22:31 UTC, Z3rio commented on server/main.lua
> +					MySQL.insert('INSERT INTO billing (identifier, sender, target_type, target, label, amount) VALUES (?, ?, ?, ?, ?, ?)', {targetIdentifier, senderIdentifier, 'society', sharedAccountName, label, a
Yeah, true, I'll remove the code duplication.

2024-06-20 13:41 UTC, Z3rio commented
@Gellipapa Why should `if not xTarget then return end` be preferred?
Just checking if xTarget isn't nil (aka the way its done right now) is a lot more logical, more readable, does the same thing, and takes less lines.

2024-06-20 19:41 UTC, Gellipapa commented
> @Gellipapa Why should `if not xTarget then return end` be preferred? Just checking if xTarget isn't nil (aka the way its done right now) is a lot more logical, more readable, does the same thing, and takes less lines.

@Z3rio  Hi! The basic logic is to deny because it will always be much more readable to get the actual result than to always write it in IF, look it up. In most cases it's most readable if you exclude everything line by line and at the end you only have the actual result before you always exit the code. This is a common and used method in software development.

2024-06-20 22:12 UTC, Gellipapa approved these changes
Thanks for fixes i merged.

2024-06-20 22:12 UTC, merged